language: python

sudo: false
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy
  - TOXENV=flake8

install:
  - travis_retry pip install tox coveralls

script:
  - tox

after_success:
  - coveralls
