language: python

sudo: false
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy
  - TOXENV=flake8
  - TOXENV=cov

install:
  - travis_retry pip install tox

script:
  - tox
